# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Нзавания товара')),
                ('product_overview', models.TextField(verbose_name='Обзор')),
                ('product_image', models.ImageField(upload_to='images/news/', verbose_name='Картинка товара')),
                ('product_prices', models.IntegerField(verbose_name='Цена')),
                ('product_date_create', models.DateTimeField(auto_now_add=True)),
                ('product_date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
