# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='images/product/', verbose_name='Картинка товара'),
        ),
    ]
