# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20170604_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_overview',
            field=models.TextField(blank=True, verbose_name='Обзор'),
        ),
    ]
