# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 08:10
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20170604_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_overview',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Обзор'),
        ),
    ]
