# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20170609_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_slug',
        ),
    ]
