# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_category_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_slug',
        ),
    ]
