# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_product_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
