# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_public',
        ),
    ]
