# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20170609_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='На складе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Доступен'),
        ),
    ]
