# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 08:48
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20170611_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_overview',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Обзор'),
        ),
    ]
