# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 09:33
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20170611_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_overview_anons',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_overview',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Обзор'),
        ),
    ]
